employee-ps/employee/forms/__init__.py
from employee.forms.register import RegisterationForm
from employee.forms.login import LoginForm

employee-ps/employee/forms/login.py
from wtforms import Form, StringField, PasswordField, validators

class LoginForm(Form):
	email = StringField('Email', [validators.Length(min=1, max=100)])
	password = PasswordField('Password', [validators.Length(min=1), validators.DataRequired()])

employee-ps/employee/forms/register.py
from wtforms import Form, StringField, TextAreaField, PasswordField, validators

class RegisterationForm(Form):
	name = StringField('Name', [validators.Length(min=1, max=100)])
	email = StringField('Email', [validators.Length(min=1, max=100)])
	address = TextAreaField('Address', [validators.Length(max=500)])
	password = PasswordField('Password', [validators.DataRequired(), validators.EqualTo('confirm', message="Password didn't matched.")])
	confirm = PasswordField('Confirm Password')

employee-ps/employee/views/home.py
from flask import Blueprint, render_template

home_bp = Blueprint('home_bp', __name__)

@home_bp.route('/')
def home():
	return render_template('home.html')

employee-ps/employee/views/logout.py
from flask import Blueprint, session, flash, redirect, url_for
from employee.views.login_check import is_loggedin

logout_bp = Blueprint('logout_bp', __name__)

@logout_bp.route('/logout')
@is_loggedin
def logout():
	session.clear()
	flash('You have succesfully logged out', 'success')
	return redirect(url_for('login_bp.login'))

employee-ps/employee/views/profile.py
from flask import Blueprint, render_template, session
from employee.models import Employee

profile_bp = Blueprint('profile_bp', __name__)

@profile_bp.route('/profile')
def profile():
	emp = Employee.query.filter_by(id=session['id']).first()
	return render_template('profile.html', emp=emp)

employee-ps/employee/views/register.py
from flask import Blueprint, render_template, request, flash, session, redirect, url_for
from employee.forms.register import RegisterationForm
from employee import db
from employee.models.employee import Employee

register_bp = Blueprint('register_bp', __name__)

@register_bp.route('/register', methods=['GET', 'POST'])
def register():
	form = RegisterationForm(request.form)
	if request.method == 'POST' and form.validate():
		name = request.form['name']
		email = request.form['email']
		address = request.form['address']
		password = request.form['password']
		new_emp = Employee(name, email, address, password)
		db.session.add(new_emp)
		db.session.commit()
		flash('You have been successfully registered', 'success')
		return redirect(url_for('home_bp.home'))
	return render_template('register.html',form=form)	

employee-ps/employee/templates/includes/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

employee-ps/employee/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}

employee-ps/employee/templates/includes/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">StrongMan</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="{{ url_for('home_bp.home') }}">Home</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('attendance_bp.attendance') }}">Attendance</a></li>
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if session.logged_in %}
        <li class="nav-item"><a class="nav-link" href="{{ url_for('profile_bp.profile') }}">Profile</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('logout_bp.logout') }}">Logout</a></li>
      {% else %}
        <li class="nav-item"><a class="nav-link" href="{{ url_for('register_bp.register') }}">Register</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('login_bp.login') }}">Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>